### ISSUE TITLE
Example bundle file should only declare necessary config options

### ISSUE THREAD

**Issue by ryan-beisner** [trilioData/triliovault-cfg-scripts#105]
The configuration options which are defined in the example bundle yaml file should only declare necessary items.  Redefining a charm default config option is not necessary.

https://github.com/trilioData/triliovault-cfg-scripts/blob/master/juju-charms/trilio_test_bundle.yaml#L168-L189

**Comment by abhijeetpatra** [comment]
Updated the bundle file with no config parameters.
The example bundle file will be provided to you separately and it has max of 6 config parameters which are necessary to deploy the charm.
closing this issue.

**Comment by ryan-beisner** [comment]
Until the working example is provided, I wouldn't consider this issue closed.
